// 1. Data mapping for all directory tools & categorization metrics (Explicit Path Fixes)
const TOOLS_REGISTRY = [
    { name: "AU Cents-Per-Km Estimator", path: "/au-cents-per-km-estimator/index.html", tag: "AU TAX" },
    { name: "AU SCHADS Vehicle Allowance", path: "/au-schads-vehicle-allowance/index.html", tag: "AU LABOUR" },
    { name: "AU Superannuation Guarantee Charge", path: "/au-superannuation-charge-tracker/index.html", tag: "AU TAX" },
    { name: "US Section 179 Vehicle Deduction", path: "/us-section-179-truck-calculator/index.html", tag: "US TAX" },
    { name: "US LLC Late Tax Penalty Estimator", path: "/us-llc-late-penalty-estimator/index.html", tag: "US TAX" },
    { name: "UK Form 4A Rent Increase Tracker", path: "/uk-form-4a-rent-tracker/index.html", tag: "UK LEGAL" },
    { name: "UK Stamp Duty Bracket Estimator", path: "/uk-sdlt-bracket-estimator/index.html", tag: "UK TAX" },
    { name: "UK Section 8 Notice Calculator", path: "/uk-section-8-calculator/index.html", tag: "UK LEGAL" },
    { name: "Instagram Reels Aspect Ratio", path: "/instagram-reels-preview/index.html", tag: "MEDIA" },
    { name: "YouTube Shorts UI Safe Zone", path: "/shorts-ui-safe-zone/index.html", tag: "MEDIA" },
    { name: "TikTok Ad Safe Zone Analyzer", path: "/tiktok-ad-safe-zone/index.html", tag: "MEDIA" },
    { name: "Shopify Metafields Parser", path: "/shopify-metafields-parser/index.html", tag: "ECOM" }
];

function injectAdvertisementCode(containerId) {
    const adSlot = document.getElementById(containerId);
    if (!adSlot) return;

    const networkOneCode = ``;
    const networkTwoCode = ``;

    let finalAdHTML = "";
    if (networkOneCode.trim() !== "") finalAdHTML += networkOneCode;
    if (networkTwoCode.trim() !== "") finalAdHTML += networkTwoCode;

    if (finalAdHTML.trim() !== "") {
        adSlot.innerHTML = finalAdHTML;
        adSlot.classList.add("has-ads");
    }
}

function buildGlobalHeader() {
    const navLinksHTML = TOOLS_REGISTRY.map(tool => 
        `<a href="${tool.path}" class="tool-nav-item">${tool.name}</a>`
    ).join('');

    return `
        <header class="global-navbar-shell global-layout-wrapper">
            <div class="global-logo-row">
                <a href="/" class="global-logo-link">CoreMetricSuite</a>
                <span class="global-version-tag">v1.0.4 - Direct Multi-Jurisdictional Utilities</span>
            </div>
            <nav class="tool-slider-nav">
                ${navLinksHTML}
            </nav>
        </header>
        <div class="ad-container-slot" id="top-global-ad"></div>
    `;
}

function buildGlobalFooter() {
    return `
        <div class="ad-container-slot" id="bottom-global-ad"></div>
        
        <div class="compliance-disclaimer-box global-layout-wrapper">
            <p class="disclaimer-header">⚠️ Automated Financial & Legal Disclaimer</p>
            All calculations, estimations, data points, and outputs generated by CoreMetricSuite tools are provided for informational and educational purposes only. This web application does not constitute official accounting, tax, legal, or professional business advice. While we endeavor to keep rates accurate and reflective of local jurisdictional updates, parameters can change. Always verify mathematical models against official government portals or consult a certified professional before rendering financial decisions.
        </div>

        <footer class="global-footer-shell global-layout-wrapper">
            <p class="footer-branding"><strong>CoreMetricSuite Utilities Platform</strong> - Free browser-side business analysis tools.</p>
            <div class="footer-nav-row">
                <a href="/about.html" class="footer-link">About Us</a>
                <a href="/privacy-policy.html" class="footer-link">Privacy Policy</a>
                <a href="/terms.html" class="footer-link">Terms of Service</a>
                <a href="/contact.html" class="footer-link">Contact Support</a>
            </div>
            <p class="footer-copyright">&copy; 2026 CoreMetricSuite. All calculation scripts execute serverless client-side.</p>
        </footer>
    `;
}

function buildSuggestions() {
    const activePath = window.location.pathname;
    const currentTool = TOOLS_REGISTRY.find(t => activePath.includes(t.path));
    if (!currentTool) return '';

    const matches = TOOLS_REGISTRY.filter(t => t.tag === currentTool.tag && t.path !== currentTool.path);
    const displayList = matches.length >= 2 ? matches : TOOLS_REGISTRY.filter(t => t.path !== currentTool.path).slice(0, 3);

    const suggestionItemsHTML = displayList.map(t => `
        <a href="${t.path}" class="suggestion-card">
            <span class="suggestion-tag">${t.tag}</span>
            <strong class="suggestion-name">${t.name}</strong>
        </a>
    `).join('');

    return `
        <section class="related-suggestions-box global-layout-wrapper">
            <h3 class="suggestions-title">Related CoreMetric Utilities</h3>
            <p class="suggestions-subtitle">Based on your current operations, you may also need these calculators:</p>
            <div class="suggestions-grid">
                ${suggestionItemsHTML}
            </div>
        </section>
    `;
}

document.addEventListener("DOMContentLoaded", () => {
    const body = document.body;
    const activePath = window.location.pathname;
    
    // Automatically apply dark styling layout if we are inside a subfolder tool [1]
    const isToolPage = TOOLS_REGISTRY.some(tool => activePath.includes(tool.path));
    if (isToolPage) {
        body.classList.add("dark-theme-page");
    }

    body.insertAdjacentHTML("afterbegin", buildGlobalHeader());

    const targetMainWrapper = document.querySelector('main') || body;
    targetMainWrapper.insertAdjacentHTML("beforeend", buildSuggestions());
    body.insertAdjacentHTML("beforeend", buildGlobalFooter());

    injectAdvertisementCode("top-global-ad");
    injectAdvertisementCode("bottom-global-ad");
});
